# Generated by Django 4.2.2 on 2023-11-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADM", "Administrador"), ("OPS", "Operador")],
                default=None,
                max_length=3,
            ),
            preserve_default=False,
        ),
    ]
