# Generated by Django 4.2.2 on 2023-10-23 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import alerts.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("surname", models.CharField(max_length=64)),
                (
                    "telephone",
                    models.CharField(max_length=32, validators=[alerts.utils.only_int]),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CLA", "Claro"),
                            ("PER", "Personal"),
                            ("MOV", "Movistar"),
                            ("TUE", "Tuenti"),
                            ("OTH", "Other"),
                        ],
                        max_length=3,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                (
                    "state",
                    models.CharField(
                        choices=[("N", "New"), ("A", "Attended"), ("C", "Closed")],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "observations",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alerts.beneficiary",
                        verbose_name="beneficiary",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="operator",
                    ),
                ),
            ],
        ),
    ]
