# Generated by Django 4.2.2 on 2023-11-26 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_role"),
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="description",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.CreateModel(
            name="BeneficiaryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8)),
                ("description", models.CharField(max_length=8)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="alerts.beneficiarytype",
                verbose_name="type",
            ),
        ),
    ]
