# Generated by Django 4.2.2 on 2023-11-30 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("alerts", "0002_beneficiary_description_beneficiarytype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="operator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="operator",
            ),
        ),
        migrations.AlterField(
            model_name="beneficiary",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="alerts.beneficiarytype",
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="beneficiarytype",
            name="description",
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name="AlertType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8)),
                ("description", models.CharField(max_length=32)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="alert",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="alerts.alerttype",
                verbose_name="type",
            ),
        ),
    ]
