# Generated by Django 4.2.2 on 2023-12-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0003_alter_alert_operator_alter_beneficiary_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="datetime_attended",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="datetime_closed",
            field=models.DateTimeField(null=True),
        ),
    ]
