# Generated by Django 4.2.2 on 2023-12-01 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_role"),
        ("alerts", "0004_alert_datetime_attended_alert_datetime_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="organization",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.organization",
                verbose_name="organization",
            ),
            preserve_default=False,
        ),
    ]
