# Generated by Django 4.2.2 on 2023-12-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0005_alert_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="message_sid",
            field=models.CharField(max_length=34, null=True),
        ),
    ]
