# Generated by Django 4.2.2 on 2024-06-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0006_alert_message_sid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="message_sid",
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AlterField(
            model_name="alert",
            name="observations",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
