# Generated by Django 4.2.2 on 2024-06-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0007_alter_alert_message_sid_alter_alert_observations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiary",
            name="company",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CLA", "Claro"),
                    ("PER", "Personal"),
                    ("MOV", "Movistar"),
                    ("TUE", "Tuenti"),
                    ("OTH", "Other"),
                ],
                default="OTH",
                max_length=3,
            ),
        ),
    ]
